server:
  port: 8095

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demodb
    username: demo
    password: demo123
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
    defer-datasource-initialization: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.example.enumapp: INFO
