CREATE TABLE IF NOT EXISTS cache_demo_products (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   VARCHAR(100) NOT NULL,
    price  INT NOT NULL,
    stock  INT NOT NULL
);

DELETE FROM cache_demo_products;

INSERT INTO cache_demo_products (name, price, stock) VALUES
    ('Keyboard', 49000, 10),
    ('Mouse', 29000, 20),
    ('Monitor', 219000, 5);
