CREATE TABLE IF NOT EXISTS qdsl_demo_orders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name   VARCHAR(100) NOT NULL,
    status          VARCHAR(20),
    pay_method      VARCHAR(20),
    user_grade      VARCHAR(20) NOT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS qdsl_demo_order_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT NOT NULL,
    product_name    VARCHAR(100) NOT NULL,
    sku             VARCHAR(50) NOT NULL,
    quantity        INT NOT NULL
);
