server:
  port: 8112

spring:
  datasource:
    url: jdbc:h2:mem:cacheboth;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  h2:
    console:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379

app:
  cache:
    # both | caffeine | redis  (프로필로 바꿔도 됨)
    mode: both

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.example.cacheapp: INFO
    com.example.cacheapp.product.ProductMapper: DEBUG
    com.example.cacheapp.config.MybatisSqlLoggingInterceptor: INFO
