server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demodb
    username: demo
    password: demo123
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.security: INFO
